### ISSUE TITLE
Non-uniform grid spacing?

### ISSUE THREAD

**Issue by anriseth** [JuliaDiffEq/DiffEqOperators.jl#17]
Is there a plan for implementing support for non-uniform grid spacing? I see the finite difference scheme used here is named after Fornberg. If I remember correctly, the Fornberg paper supports this?

**Comment by shivin9** [comment]
Hi,
Yes it does support non-uniform spacing and we might support in the future. Problems come when we try to create a transpose operator. The whole function (stencils) changes and we don't know how to implement it without a matrix.

**Comment by ChrisRackauckas** [comment]
It's fine to have no transpose in that case. non-uniform with the BC handling is super useful by itself, and many iterative solvers don't need the transpose.

**Comment by shivin9** [comment]
Upon further thought, we can get the transposed stencils very easily actually (except for `:periodic` maybe)
We can generate the 'essential' full matrix linear operator ie. one which is much smaller is size (`O((derivative_order+approximation_order)^2)`) and since it contains the essential information about all the coefficients, we can take it's transpose and get the transposed stencils. eg. 
``` julia
julia> A = LinearOperator{Float64}(2,4,1.0,100,:D0,:D0);
julia> full(A,5)
5×5 Array{Float64,2}:
 -2.5         1.33333    -0.0833333   0.0         0.0      
  1.33333    -2.5         1.33333    -0.0833333   0.0      
 -0.0833333   1.33333    -2.5         1.33333    -0.0833333
  0.0        -0.0833333   1.33333    -2.5         1.33333  
  0.0         0.0        -0.0833333   1.33333    -2.5      
```
`full(A,5)'`, in this case the same matrix, will have the transposed stencils which we can store for fast calculation of transposes.
Using `A'` will just meaning changing a flag variable in the LinearOperator to start using the transposed stencils created at initialization.

**Comment by ChrisRackauckas** [comment]
Don't worry about this until way way later.

**Comment by dextorious** [comment]
For the moment, anyone who needs the transpose can just use the full matrix operator, so the functionality is still there, just not optimal. With that caveat, supporting non-uniform spacing is actually very straightforward.

**Comment by shivin9** [comment]
work going on here https://github.com/JuliaDiffEq/DiffEqOperators.jl/pull/49
