### ISSUE TITLE
Nonlinear Robin boundary conditions

### ISSUE THREAD

**Issue by Jvanrhijn** [JuliaDiffEq/DiffEqOperators.jl#211]
I've run into a situation where I need to simulate an SPDE with a nonlinear (well, quasilinear) Robin boundary condition at the right endpoint of the domain:

> u' + u*exp(-u^2) = 0.

I can't find anywhere in the docs if this functionality is provided. If it's not, I'd love to help implement it, although I only started working with Julia two days ago so I don't think I'd be of much help...

Cheers.

**Comment by ChrisRackauckas** [comment]
You'd just have to write a way to invert that to get the extension operator (i.e. ghost points), or write the SPDE in mass matrix form. The former should be simpler here, since if you discretize the `u'` you get a formula for the endpoint from the non-endpoint value if you expand at the non-endpoint value.

**Comment by Jvanrhijn** [comment]
Could you elaborate a bit? I'm not sure where to start here, since the extension operators are linear here, while I require a nonlinear operator.

**Comment by ChrisRackauckas** [comment]
If you can solve for the boundary value then you can do the same thing. Here, `u' -> (u[2]-u[1])/dx`, solve for `u[1]` expanding from `u[2]`, and that's the extrapolation condition.

Or you can always enforce the condition using the mass matrix `Bu' = Au` form. Or use a DAE.

**Comment by Jvanrhijn** [comment]
Oh no yeah, I understood that bit :) I was more wondering whether you meant extending the library with this functionality, or doing something within the library as-is. Sorry if that was unclear.

At the moment I'm just redefining the BC like that on every iteration, which is... not ideal, but it works well enough for my purposes.

**Comment by ChrisRackauckas** [comment]
It would be nice to have a real solution in the library. It's less clear what that looks like, but I'm open to ideas!

**Comment by Jvanrhijn** [comment]
As far as the interface goes, it seems to me that it's easy to generalize to nonlinear Robin BCs in the by just replacing the action of the BC operator to be nonlinear, i.e.
```
bc * u --> bc(u),
```
since a nonlinear Robin BC in general looks like 

> f(u, u') = 0.

You could keep the overloaded `*` operator for backwards compatibility. It's even easier if the BC is of the form 

> u' = f(u),

since then you only have to solve for the boundary value as `u[end] = u[end-1] + dx * f(u[end])`. It's not entirely clear how to generalize this to higher-order Robin BCs  though.

Is this feasible at all? I'm afraid I don't really have the Julia knowledge to figure out the library at the moment.

**Comment by ChrisRackauckas** [comment]
I think the latter is fine already. The current implementation is lazy, so the idea is that you can always compute the coefficients on the fly and efficiently generate new L*Q(u)*u whenever u changes. I don't think we need to embed the functions into Q as long as all of these are only composing lazily.

The general form of f(u,u')=0 is what I worry about. If we don't know how to invert it, then I don't know how to write the BC in this form, and instead think you can only generally handle that in the form where you have a mass matrix or constraint equation.

------------------------------------------------
Applied Mathematics Instructor, Massachusetts Institute of Technology
Senior Research Analyst, University of Maryland, Baltimore, School of Pharmacy, Center for Translational Medicine
On 1/2/2020 7:12:12 PM, Jesse van Rhijn <notifications@github.com> wrote:
As far as the interface goes, it seems to me that it's easy to generalize to nonlinear Robin BCs in the by just replacing the action of the BC operator to be nonlinear, i.e.
bc * u --> bc(u),
since a nonlinear Robin BC in general looks like
f(u, u') = 0.
You could keep the overloaded * operator for backwards compatibility. It's even easier if the BC is of the form
u' = f(u),
since then you only have to solve for the boundary value as u[end] = u[end-1] + dx * f(u[end]). It's not entirely clear how to generalize this to higher-order Robin BCs though.
Is this feasible at all? I'm afraid I don't really have the Julia knowledge to figure out the library at the moment.

**Comment by Jvanrhijn** [comment]
I think the only way to handle that general form would really be to solve for u' iteratively, and use that to generate a new Q(u). It's slow, but I can't see any other way to do it.

In any case, you can close this if you like, since my problem is essentially solved by just generating new Q every time step.

Thanks for your suggestions!

**Comment by ChrisRackauckas** [comment]
Yes, the general form would need to specify an implicit equation and use an iterative method to solve it. You'd have to use something like DAE in that case.
