### ISSUE TITLE
How Dirichlet boundary conditions are imposed

### ISSUE THREAD

**Issue by francispoulin** [JuliaDiffEq/DiffEqOperators.jl#40]
I was putting together a notebook to explain the Diffusion example in DiffEqOperator and found that the boundary conditions are not imposed the way that I thought.

https://github.com/francispoulin/DiffEqOperators.jl/blob/master/docs/DiffusionEqTutorial.ipynb

It seems that the boundary conditions are not not imposed considering that the ends of the boundaries are included in their domain.  

One way to do this is to pick a staggered grid so that you have points in the centre of each cells, but it might be that the BC's are still not imposed correctly.

I would think that the best way of doing this is to assume that the end points are contained in the domain and then worry about whether you have Dirichlet, Neuman or Mixed BCs.  

Has anyone thought about how to do this and can we fix this soon or is this a big task?

**Comment by ChrisRackauckas** [comment]
From the Gitter:

**Comment by ChrisRackauckas** [comment]
But Dirichlet is a little weird, with that implementation what should we do if the BCs don't match what you put on the ends of the vector?

**Comment by ChrisRackauckas** [comment]
From Gitter:

the left BC for Dirichlet is here: https://github.com/JuliaDiffEq/DiffEqOperators.jl/blob/master/src/derivative_operators/boundary_operators.jl#L53
for i in 1 : A.boundary_point_count[1]
for each point where the boundary would go over the edge
(so for 2nd order that's just the last point)
it calls dirichlet_1!(x_temp, x, A.stencil_coefs, mid, i)
https://github.com/JuliaDiffEq/DiffEqOperators.jl/blob/master/src/derivative_operators/boundary_operators.jl#L353
so that's the function to find out
x_temp[i] is the output
coeffs is the stencil [-1 2 1]
x is the initial vector
i is the current location, so at the edge it's 1
need to find out what mid is

```julia
function dirichlet_1!(x_temp::AbstractVector{T}, x::AbstractVector{T}, coeffs::SVector, mid::Int, i::Int) where T<:Real
    stencil_length = length(coeffs)
    N = length(x)
    #=
        Here we are taking the weighted sum of a window of the input vector to calculate the derivative
        at the middle point. Once the stencil goes out of the edge, we assume that it's has a constant
        value outside for all points.
    =#
    xtempi = zero(T)
    @inbounds for idx in 1:stencil_length
        xtempi += coeffs[idx] * x[limit(i - (mid-idx), N)]
    end
    x_temp[i] = xtempi
end
```

so something about x[limit(i - (mid-idx), N)] is making the x's all do something
but whatever it is, that's a weird line of code and should be changed.
it should have the user's BC there
and basically if i-idx<1, it's a point over the boundary and should use the BC value.

so my guess is it needs to be something like
```julia
     @inbounds for idx in 1:stencil_length
        loc = i - idx
        if loc < 0
           xtempi += coeffs[idx]*bc_right
        else
           xtempi += coeffs[idx] * x[i-idx]
         end
    end
```
then the function needs to get passed bc_right
err, left
mb
so the function call `dirichlet_1!(x_temp, x, A.stencil_coefs, mid, i)`
needs to change
the type is defined here: https://github.com/JuliaDiffEq/DiffEqOperators.jl/blob/master/src/derivative_operators/derivative_operator.jl#L57
so you can see that A.boundary_condition is where that tuple is stored
so it should be passed
`dirichlet_1!(x_temp, x, A.stencil_coefs, mid, i,A.boundary_condition[1])`
the function should be expanded
and it should replace the loop to put in the BC like that

**Comment by ChrisRackauckas** [comment]
Example problem: https://github.com/francispoulin/DiffEqOperators.jl/blob/master/docs/DiffusionEqTutorial.ipynb

**Comment by ChrisRackauckas** [comment]
Here's a review of the BCs:

- `Dirichlet0` assumes the boundary points are the first points off the boundary
- `Dirichet` assumes the last points are the boundary points and fixes them
- `Neumann0` assumes the boundary points are the last points on the vector
- `Neumann` assumes the boundary points are the last points on the vector
- `Periodic`  assumes the first point is a BC and the last point is not (since they would be the same.

We should make these all `CenterPeriodic`, etc., and then have `Periodic` be the case where the boundary is included in the ends (and do error checks).
